- name: app setup
  include_role:
    name: common
    tasks_from: app-setup

- name: maven setup
  include_role:
    name: common
    tasks_from: maven

- name: import mysql data
  include_role:
    name: common
    tasks_from: mysql-data

- name: systemd setup
  include_role:
    name: common
    tasks_from: systemd