    - name: app setup
      include_role: 
        name: common
        tasks_from: app-setup

    - name: maven setup
      include_role: 
        name: common
        tasks_from: maven

    - name: import data
      include_role: 
        name: common
        tasks_from: data

    - name: systemd setup
      include_role:
        name: common
        tasks_from: systemd