- name: Install MySQL server
  ansible.builtin.dnf:
    name: mysql-server
    state: installed

- name: start mysql server
  ansible.builtin.systemd_service:
    name: mysqld
    state: started
    enabled: yes

- name: setup root password
  ansible.builtin.command: mysql_secure_installtion --set-root-pass RoboShop@!