- name: stop to service
  ansible.builtin.service: 
    name: "{{ component }}"
    state: stopped
  
- name: remove /app directrory
  ansible.builtin.file:
    state: absent
    path: /app

- name: create /app directrory
  ansible.builtin.file:
    state: directrory
    path: /app

- name: download application
  ansible.builtin.unarchive:
    src: "https://roboshop-artifacts.s3.amazonaws.com/{{ component }}-v3{{ app_version }}.zip"
    dest: /app
    remote_src: yes

- name: install dependencies 
  community.general.npm:
    path: /app

- name: restart {{ componenet }}
  ansible.builtin.service:
    name: "{{ component }}"
    state: restarted
     

